@startuml
!define MyBackgroundColor #lightblue
!define MyBorderColor #005f87

skinparam class {
  BackgroundColor MyBackgroundColor
  BorderColor MyBorderColor
}
skinparam classAttributeIconSize 0


class City{
  -victory_points
  -money
  -treasur
  -ressources
  -number_of_shields
  -scientific_symbols : struct symbol[]

  +trade()
  +constructBuilding()
  +constructWonder()
  +discardCard()
  +checkMilitaryVictory()
  +checkScientificVictory()
}

class Player{
  -type
  -isItHisTurn : bool
  +play()
}

struct ScientificSymbol{
  +name
  +amount
  
  +add()
}

class Card{
  -name
  -cost[]
  -owner
  -effects[]
  
  +getPrice()
}


class Building{
  -age
  -visible : bool
  -type
  -chain_cost
  
  +build()
  -useEffects()
  -discardIt()
  
  
}

class Wonder{
  -activated : bool
  
  +build()
  +select()
  -useEffects()
}

class ProgressToken{
  -on_the_board : bool
  +useEffects()
}

class ConflictPawn{
  -current_position
  
  +move()
}

Card <|-- Building
Card <|-- Wonder
Card <|-- ProgressToken
City o-- "*" Card
City *-- "*" ScientificSymbol
City *-- "1" Player
City "2" --- "1" ConflictPawn
@enduml
