@startuml
!define MyBackgroundColor #lightblue
!define MyBorderColor #005f87

skinparam class {
  BackgroundColor MyBackgroundColor
  BorderColor MyBorderColor
}
skinparam classAttributeIconSize 0


class City{
  -victory_points
  -money
  -treasur
  -number_of_shields
  -scientific_symbols : struct symbol[]

  +trade()
  +constructBuilding()
  +constructWonder()
  +discardCard()
  +checkMilitaryVictory()
  +checkScientificVictory()
}

class Player{
  -type
  -isItHisTurn : bool
  +play()
}

struct ScientificSymbol{
  +name
  +amount
  
  +add()
}

class Card{
  -name
  -cost[]
  -owner
  
  +getPrice()
}


class Building{
  -age
  -visible : bool
  -type
  -chain_cost
  
  +build()
  -discardIt()
  
  
}

class Wonder{
  -activated : bool
  
  +build()
  +select()
}

class ProgressToken{
  -on_the_board : bool
}

class ConflictPawn{
  -current_position
  
  +move()
}


class Ressources{
  -name
  -amount
  -price
  
  +add()
  +getPrice()
  +updatePrice()
}

class Effect{
  
}

class IncreaseRessources{
  -ressource_name
  +effect()
}

class IncreaseVictoryPoint{
  +effect()
}

class AddScientificSymbol{
  -symbol_name
  +effect()
}

class AddCoin{
  +effect()
}

class AddShield{
  +effect()
}


class ChangeMarketRule{
  -ressource_name
  +effect()
}


Effect --* IncreaseRessources
Effect --* AddCoin
Effect --* IncreaseVictoryPoint
Effect --* AddScientificSymbol
Effect --* AddShield
Effect --* ChangeMarketRule

Card "*" --- "*" Effect
Card <|-- Building
Card <|-- Wonder
Card <|-- ProgressToken

City o-- "*" Card
City *-- "*" ScientificSymbol
City *-- "1" Player
City "2" --- "1" ConflictPawn
City *-- "*" Ressources
@enduml
