@startuml
!define MyBackgroundColor #lightblue
!define MyBorderColor #005f87

skinparam class {
  BackgroundColor MyBackgroundColor
  BorderColor MyBorderColor
}
skinparam classAttributeIconSize 0


class Board {
  -age : int
  +advancedAge()
  +updateMarket()
}

class Game {
  -age : int
  -board : Board*
  -players[2] : Player* 
  -isReplaying : bool 
  -deck : DeckPile* 
  -updateConflictPawn() : bool 
  -winner : Player* 
  +bool endTurn() : bool
  +advanceAge() : void
  +startGame() : void
  +getTurnPlayer() : Player& 
  +getOtherPlayer() : Player& 
  +bool playAge() : void
  +playTurn() : void
  +startMenu() : void
}

enum AiLevel{
    EASY,
    MEDIUM,
    HARD
}

class Player{
  - city : City&
  -isAI : bool
  -aiLevel : AiLevel
  -name : string
  +selectCard(Game& game, MarketDeck& marketDeck) : DeckElement*
  +buyCard(Game& game, Card& card,MarketDeck& marketDeck) : bool
  +play(Game& game) : void
  +chooseWonder(Wonder[] availableWonders) : void
}

class DeckPile{
 -buildings : pair[Building[], Building[]]
 -wonders : Wonder[]
 -progress_tokens : pair[ProgressToken[], ProgressToken[]]
 
 +advanceAge(int age) : void
}
class City {
 -military_position : int
  -treasury : int
  -number_of_shields : int
  -player_turn : bool
  +play()
  +constructBuilding(Building* building) : Building&
  +constructWonder(Wonder* wonder) : Wonder&
  +discardCard(Card* card)
  +checkMilitaryVictory() : Bool
  +checkScientificVictory() : Bool
  +buy(card& c) : Bool
}

class ScientificSymbol{
  -symbol_type: SymbolType
  -count: int 
  
  +add()
}

class Card{
  -name : string
  -ressources : Ressource**
  -taille_ressources : int
  +get_price_ressources const () : Ressources**
} 



class Building{
  -age : int
  -visible : bool
  -type : couleur
  -chain_cost : int
  +build()
  -discardIt()
  
  
}

class Wonder{
  -activated : bool
  
  +getStatus() : bool
  +activate() : void
}

class ProgressToken{
  -on_the_board : bool
  +onTheBoard() : bool
  +statusSwitch() : void
}

class ConflictPawn{
  -current_position
  
  +move()
}


class MarketDeck{
  -age : int
  -first_buildings : DeckElement**
  -nb_first_buildings : int
  +constructNewAgeMarket()
  +class iterator()
}
class DeckElement{
  -right_son : DeckElement*
  -left_son : DeckElement*
  -right_father : DeckElement*
  -left_father : DeckElement*
  -building : Building&
  -visible : bool
  +getRightSon() : DeckElement*
  +getLeftSon() : DeckElement*
  +getRightFather() : DeckElement*
  +getLeftFather() : DeckElement*
  +getBuilding() : Building&
  +isVisible() : bool
  +setVisible() : void
  +operator++(int) : DeckElement*
  +operator++() : DeckElement*
}

class Ressource{
  -type : RessourceType
  -amount : int
  -price : int
  
  +addMaterials() : void
  +getPrice() : int
  +getAmount() : int
  +updatePrice() : void
}
abstract class Effect <<abstract>>{
    + apply(Game& game) : void <<abstract>>
    + endEffect(Game& game) : void <<abstract>>
    + eachTurnEffect(Game& game, Card& card) : void <<abstract>>
    + setParameters(int[], string[]) : void <<abstract>>
}

class ExempleEffect {
  + apply(Game& game) : void
  + setParameters(int[], string[]) : void
}
/'
class InstantReplaying{
  +apply()
}

class AdversaryPaysMoneyToBank{
  +apply()
}
class AddVictoryPoint{
  +apply()
}

class MoveConflictPawn{
  +apply()
}
class AddRessource{
  +apply()
}

class DiscardAdversaryBrownCard{
  +apply()
}

class AddRessourceChoice{
  +apply()
}
class BuildOneDiscardedBuilding{
  +apply()
}
class ChooseOneProgressTokenWithinThreeDiscarded{
  +apply()
}

class EarnFourMoneyPerBuildingChaining{
  +apply()
}

class NewWondersHaveInstantReplaying{
  +apply()
}

class MoveConflictPawnOneMorePerNewRed{
  +apply()
}

class EarnThreeVictoryPointsPerProgressTokenAtEndGame{
  +apply()
}

class TakeScientificSymbol{
  +apply()
}

class TakeAdversaryTradeMoney{
  +apply()
}

class WonderCostReducedByX{
  +apply()
}



class EarnXMoneyPerMostAtConstruct{
  +apply()
}

class EarnXMoneyPerWonderAtConstruct{
  +apply()
}

class EarnXVictoryPointPerMostWonderAtEndGame{
  +apply()
}

class EarnXVictoryPointPerGoldAndBrownMostAtEndGame{
  +apply()
}

class EarnXVictoryPointPerThingMostAtEndGame{
  -thing
  +apply()
}

class ChangeMarketRule{
  +apply()
}'/

class Instanciator{
-cards_file
-game_parameters
-buildings_instanciator
-wonders_instanciator
-progress_tokens_instanciator

}

class File {
-file_path
-file
-readFile()

}

Instanciator *-- File

enum SymbolType {
    COMPASS, 
    QUILL, 
    WHEEL, 
    TABLET, 
    SCALE, 
    BOWL, 
    GLOBE
}

enum ResourceType {
    WOOD, 
    STONE,
    CLAY, 
    PAPER, 
    GLASS
}

enum BuildingType {
  Yellow,
  Brown,
  rey,
  Purple, 
  Green,
  Red,
  Blue
}
Player *-- "1" City
Board o-- "5" ProgressToken 
Board *-- "1" MarketDeck
Board *-- "1" ConflictPawn

MarketDeck "1" o-- "*" DeckElement

DeckElement o-- "1" Building
/'Effect <|--  AddRessourceChoice
Effect <|--  ChangeMarketRule
Effect <|--  EarnXVictoryPointPerThingMostAtEndGame
Effect <|--  EarnXVictoryPointPerGoldAndBrownMostAtEndGame
Effect <|--  EarnXVictoryPointPerMostWonderAtEndGame
Effect <|--  EarnXMoneyPerWonderAtConstruct
Effect <|--  EarnXMoneyPerMostAtConstruct
Effect <|--  WonderCostReducedByX
Effect <|--  TakeAdversaryTradeMoney
Effect <|--  TakeScientificSymbol
Effect <|--  EarnThreeVictoryPointsPerProgressTokenAtEndGame
Effect <|--  MoveConflictPawnOneMorePerNewRed
Effect <|--  NewWondersHaveInstantReplaying
Effect <|--  EarnFourMoneyPerBuildingChaining
Effect <|--  ChooseOneProgressTokenWithinThreeDiscarded
Effect <|--  BuildOneDiscardedBuilding
Effect <|--  DiscardAdversaryBrownCard
Effect <|--  AddRessource
Effect <|--  MoveConflictPawn
Effect <|--  AddVictoryPoint
Effect <|--  AdversaryPaysMoneyToBank
Effect <|--  InstantReplaying'/

/'DeckElement "0..1" --o "0..1" DeckElement : fils droit
DeckElement "0..1" --o "0..1" DeckElement : fils gauche
DeckElement "0..1" --o "0..1" DeckElement : père droit
DeckElement "0..1" --o "0..1" DeckElement : père gauche'/

Effect <|-- ExempleEffect
Game *-- Board
Game *-- "2" Player
Game *-- DeckPile
Card "*" --- "*" Effect
Card <|-- Building
Card <|-- Wonder
Card <|-- ProgressToken

City o-- "*" Building
City o-- "*" Wonder
City o-- "*" ProgressToken
City *-- "*" ScientificSymbol
City *-- "*" Ressource



@enduml