@startuml
!define MyBackgroundColor #lightblue
!define MyBorderColor #005f87

skinparam class {
  BackgroundColor MyBackgroundColor
  BorderColor MyBorderColor
}
skinparam classAttributeIconSize 0


class Board {
  -age : int
  +advancedAge()
  +updateMarket()
}

class City{
  -victory_points : int
  -treasur : int
  -number_of_shields : int
  -player_turn : bool
  +play()
  +constructBuilding()
  +constructWonder()
  +discardCard()
  +checkMilitaryVictory()
  +checkScientificVictory()
}

class ScientificSymbol{
  -type: SymbolType
  -count: int 
  
  +add()
}

class Card{
  -name
  -cost[]
  -owner
  
  +getPrice()
} 



class Building{
  -age
  -visible : bool
  -type
  -chain_cost
  
  +build()
  -discardIt()
  
  
}

class Wonder{
  -activated : bool
  
  +build()
  +select()
}

class ProgressToken{
  -on_the_board : bool
}

class ConflictPawn{
  -current_position
  
  +move()
}


class MarketDeck{
  +constructNewAgeMarket()
  +getLeaves()
  +updateTree()
}
class DeckElement{
  -right_son : DeckElement
  -left_son : DeckElement
  -is_root : bool
}

class Ressource{
  -type : RessourceType
  -amount : int
  -price : int
  
  +add()
  +getPrice()
  +updatePrice()
}
class Effect{
    -effect_name
}

class RessourceEffect{
  -ressource_name
  +apply()
}

class VictoryPointEffect{
  +apply()
}

class ScientificSymbolEffect{
  -symbol_name
  +apply()
}

class CoinEffect{
  +apply()
}

class ShieldEffect{
  +apply()
}


class ChangeRessourceCostEffect{
  -ressource_name
  +apply()
}

enum SymbolType {
    COMPASS, QUILL, WHEEL, TABLET, SCALE, BOWL, GLOBE
}

enum ResourceType {
    WOOD, STONE, CLAY, PAPER, GLASS
}

Board *-- "2" City
Board o-- "5" ProgressToken 
Board *-- "1" MarketDeck
Board *-- "1" ConflictPawn

MarketDeck o-- "*" DeckElement

DeckElement o-- "1" Building

Effect <|--  RessourceEffect
Effect <|--  CoinEffect
Effect <|--  VictoryPointEffect
Effect <|--  ScientificSymbolEffect
Effect <|--  ShieldEffect
Effect <|--  ChangeRessourceCostEffect

Card "*" --- "*" Effect
Card <|-- Building
Card <|-- Wonder
Card <|-- ProgressToken

City o-- "*" Building
City o-- "*" Wonder
City o-- "*" ProgressToken
City *-- "*" ScientificSymbol
City *-- "*" Ressource



@enduml
