#ifndef CHOOSEONEPROGRESSTOKENWITHINTHREEDISCARDED_H
#define CHOOSEONEPROGRESSTOKENWITHINTHREEDISCARDED_H

class City; // Déclaration anticipée de City
class Effect; // Déclaration anticipée de Effect

#endif CHOOSEONEPROGRESSTOKENWITHINTHREEDISCARDED_H
